#!/usr/bin/env bash
source $HOME/.dotfiles_var

noterr() { echo "Install iproute2/iw!"; exit 1; }
command -v {"ip","iw"} > /dev/null 2>&1 || noterr

# Icons
wifi=""
wifi_noip=""
wifi_disabled=""
lan=""
lan_noip=""
void=""

get_network() {
    if [[ $(iw "$INT_WIFI" link) != "Not connected." ]]; then
        if ip addr show "$INT_WIFI" | grep 'inet' &> /dev/null; then
            if ip addr show "$INT_WIFI" | grep 'inet' &> /dev/null; then
                status="$(iw "$INT_WIFI" link | grep SSID | awk -F':' '{print $2}')"
                icon="$(echo "$wifi")"
            else
                status="$(echo "No IP address ("$INT_WIFI")")"
                icon="$(echo "$wifi_noip")"
            fi
        else
            status="$(echo "Disconnected")"
            icon="$(echo "$wifi_disabled")"
        fi
    elif ip link show "$INT_ETH" &> /dev/null; then
        if ip addr show "$INT_ETH" | grep 'inet' &> /dev/null; then
            status="Ethernet"
            icon="$(echo "$lan")"
        else
            status="$(echo "No IP address ("$INT_ETH")")"
            icon="$(echo "$lan_noip")"
        fi
    else
        status="$(echo "Network interface not found ("$INT_ETH";"$INT_WIFI")")"
        icon="$(echo "$void")"
    fi
    echo "$icon $status"
}

get_network || echo "Cannot get network!"#; exit 1