#!/usr/bin/env bash
source $HOME/.dotfiles_var

temp_dev_path="/sys/devices/virtual/thermal"

[[ -d $temp_dev_path/$TEMP_DEV ]] && \

function get_temp() {
    temp="$(cat $temp_dev_path/$TEMP_DEV/temp)"
    temp="$(expr $temp / 1000)"
    if [[ "$temp" -lt 50 ]]; then
        icon=""
    elif [[ "$temp" -lt 60 ]]; then
        icon=""
    elif [[ "$temp" -lt 70 ]]; then
        icon=""
    else
        icon=""
    fi
    CEL=$'\xc2\xb0C'
    echo "$icon $temp$CEL"
}

get_temp || echo "$TEMP_DEV not found!"#; exit 1
