#!/usr/bin/env bash
source $HOME/.dotfiles_var

status=$(echo '{ "command": ["get_property", "pause"] }' | socat - $HOME/.config/mpv/socket | jq .data)
title="$(mpc --format '[%title%|%file%]' current)"

case $1 in
    prev) (echo 'playlist-prev' | socat - $HOME/.config/mpv/socket); exit 1
    ;;
    toggle) (echo 'cycle pause' | socat - $HOME/.config/mpv/socket); exit 1
    ;;
    stop) (echo 'quit' | socat - $HOME/.config/mpv/socket); exit 1
    ;;
    next) (echo 'playlist-next' | socat - $HOME/.config/mpv/socket); exit 1
    ;;
    status) echo $status 
    ;;
    title)
        if [[ $status = *"alse"* ]]; then
            icon=""
        else
            icon=""
        fi
        echo "$icon $(sh ~/.dwm/scripts/filter-ytfzf-title)"
    ;;
esac

case $BUTTON in 
    1) (echo 'cycle pause' | socat - $HOME/.config/mpv/socket) ;;
esac