#!/usr/bin/env bash
source $HOME/.dotfiles_var

CURRENT_MUSICPL="$($DEFAPPS_EXEC -g musicpl)"

prev="mpc -q prev"
toggle="mpc -q toggle"
stop="mpc -q stop"
next="mpc -q next"
status="mpc status"
title="$(mpc --format '[%title%|%file%]' current)"

status="$($status)"

case $1 in
    icon)
        if [[ $status = *"laying"* ]]; then
            echo ""
        else
            echo ""
        fi
    ;;
    prev) bash -c "$prev"
    ;;
    toggle) bash -c "$toggle"
    ;;
    stop) bash -c "$stop"
    ;;
    next) bash -c "$next"
    ;;
    status) echo "$status"
    ;;
    title) 
        if [[ $status = *"laying"* ]]; then
            echo "  $title $ytfzf_title"
        elif [[ $status = *"paused"* ]]; then
            echo "  $title $ytfzf_title"
        else
            echo "  $(cat ~/.cache/ytfzf/ytfzf_cur | cut -f1 -d '|' | sed 's/\[[^]]*\]//g' | sed 's/  \+//g' )" 
        fi
    ;;
    switchpl)
        [[ $status = *"laying"* ]] && bash -c "$toggle"
        if [[ $CURRENT_MUSICPL = "mpd" ]]; then
            sed -i 's_musicpl=".*"_musicpl="spotify"_' $DEFAPPS_FILE
        elif [[ $CURRENT_MUSICPL = "spotify" ]]; then
                sed -i 's_musicpl=".*"_musicpl="mpd"_' $DEFAPPS_FILE
        fi
        $EXNOTIFY_SEND -u low -i "$NOTIF_MUSIC_ICON" -r 8888 "Music Player" "Set <u>`$DEFAPPS_EXEC -g musicpl`</u> as default"
    ;;
    1) mpc -q next;;
esac