#!/usr/bin/env bash
source $HOME/.dotfiles_var
clear

R='\e[1;31m'
M='\e[1;35m'
C='\e[1;36m'
NC='\e[0m'

    echo -e "${C}Select playlist:"
    n=0
    for img in $PLAYLIST_DIR/yt-playlist/*; do
        n="$((n+1))"
        imgfilt="$(echo $img | grep -oE '[^/]+$' $1)"
        printf "${M}[${C}%s${M}] ${NC}%s\n" "$n" "$imgfilt"
        eval "img${n}=\$img"
    done
    printf "${C}---${NC}\nEnter File Index ID ${M}[${C}1${M}] ${NC}to ${M}[${C}%s${M}]${NC}: " "$n"
    read -r num
    num="$(printf '%s\n' "$num" | tr -dc '[:digit:]')"
    if [[ "$num" -le 0 ]] || [[ "$num" -gt "$n" ]]; then
        printf >&2 "\n${R}Wrong selection\n"
        exit 1
    else
        eval "IMG=\$img${num}"
        mpv $(cat $IMG)
    fi