#!/usr/bin/env bash
source $HOME/.dotfiles_var
clear

R='\e[1;31m'
M='\e[1;35m'
C='\e[1;36m'
NC='\e[0m'

        echo -e "${C}Select wallpaper:"
        n=0
        for img in $WALL_DIR/*; do
            n="$((n+1))"
            imgfilt="$(echo $img | grep -oE '[^/]+$' $1)"
            printf "${M}[${C}%s${M}] ${NC}%s\n" "$n" "$imgfilt"
            eval "img${n}=\$img"
        done
        printf "${C}---${NC}\nEnter File Index ID ${M}[${C}1${M}] ${NC}to ${M}[${C}%s${M}]${NC}: " "$n"
        read -r num
        num="$(printf '%s\n' "$num" | tr -dc '[:digit:]')"
        if [[ "$num" -le 0 ]] || [[ "$num" -gt "$n" ]]; then
            printf >&2 "\n${R}Wrong selection\n"
            exit 1
        else
            eval "IMG=\$img${num}"
            nitrogen --set-zoom-fill --save $IMG &> /dev/null
            # Write selected
            selected="$(echo "$IMG" | awk -F'wallpaper/' '{print $2}')"
            echo "$selected" > $CURRENT_WALL
            wal -i $WALL_DIR/$selected
            
            #Sync Xresources colorscheme
            cat "$HOME/.cache/wal/colors.Xresources" > "$HOME/.Xresources"
            
            #Sync termite colorscheme
            sed "100 r $HOME/.cache/wal/colors-kitty.conf" $HOME/.config/kitty/kitty.setting > $HOME/.config/kitty/kitty.conf
            
            #Wpgtk
            wpg -a $WALL_DIR/$selected
            wpg -s $selected
            
            printf "\n${C}Selected wallpaper: ${NC}$selected\n"
            # Notify success
            $EXNOTIFY_SEND -r 99 -u low -i $NOTIF_WALLY_ICON "Wallpaper" "Applied: <u>$selected</u>"
        fi
